theme       = "tokyo-night"
mode        = "split"
vcs         = "jj"
watch       = false
menu_bar = false
wrap_lines  = false
line_numbers = true
agent_notes = false
exclude_untracked = false
transparent_background = true

