vim.keymap.set("n", "<leader>q", ":q<enter>")
vim.keymap.set("n", "<leader>w", ":up<enter>")
vim.keymap.set("n", "<leader>a", ":wa<enter>")
vim.keymap.set("n", "sh", "<c-w>h")
vim.keymap.set("n", "e", "<end>")
vim.keymap.set("n", "sj", "<c-w>j")
vim.keymap.set("n", "<leader>z", "<cmd>ZenMode<enter>")
vim.keymap.set("n", "sk", "<c-w>k")
vim.keymap.set("n", "sl", "<c-w>l")
vim.keymap.set("n", "ss", "<c-w>s")
vim.keymap.set("n", "sv", "<c-w>v")
vim.keymap.set("n", "<tab>", "%")
vim.keymap.set("n", "<leader>n", ":noh<enter>")
vim.keymap.set("n", "\\", ":LazyGit<enter>")
vim.keymap.set("n", "[d", "<cmd>Lspsaga diagnostic_jump_prev<cr>")
vim.keymap.set("n", "]d", "<cmd>Lspsaga diagnostic_jump_next<cr>")
vim.keymap.set({ "n", "v" }, "<leader>r", "<cmd>Lspsaga rename<cr>")

vim.keymap.set("n", "[b", "<cmd>bprevious<cr>")
vim.keymap.set("n", "]b", "<cmd>bnext<cr>")

vim.keymap.set("n", "<leader>oo", "<cmd>ObsidianOpen<cr>")
vim.keymap.set("n", "<leader>ob", "<cmd>ObsidianBacklinks<cr>")
vim.keymap.set("n", "<leader>otd", "<cmd>ObsidianToday<cr>")
vim.keymap.set("n", "<leader>otm", "<cmd>ObsidianTomorrow<cr>")
vim.keymap.set("n", "<leader>oyd", "<cmd>ObsidianYesterday<cr>")
vim.keymap.set("n", "<leader>os", "<cmd>ObsidianSearch<cr>")
