local opts = { silent = true }
vim.keymap.set("n", "<leader>q", ":q<enter>", opts)
vim.keymap.set("n", "<leader>w", ":up<enter>", opts)
vim.keymap.set("n", "<leader>a", ":wa<enter>", opts)
vim.keymap.set("n", "sh", "<c-w>h", opts)
vim.keymap.set("n", "e", "<end>", opts)
vim.keymap.set("n", "sj", "<c-w>j", opts)
vim.keymap.set("n", "sk", "<c-w>k", opts)
vim.keymap.set("n", "sl", "<c-w>l", opts)
vim.keymap.set("n", "ss", "<c-w>s", opts)
vim.keymap.set("n", "sv", "<c-w>v", opts)
vim.keymap.set("n", "<tab>", "%", opts)
vim.keymap.set("n", "<leader>n", ":noh<enter>", opts)
vim.keymap.set("n", "\\", ":LazyGit<enter>", opts)
vim.keymap.set("n", "<leader>f", ":Telescope find_files<enter>", opts)
