require('settings')
require('mappings')
require('plugins/packer')
require('plugins/cmp')
require('plugins/file-tree')
-- require('plugins/git')
require('plugins/file-fuzzy')
require('plugins/autopairs')
require('style')
require('plugins/format')

