local map = vim.api.nvim_set_keymap
local default_opts = { noremap = true, silent = true }

local cmd = vim.cmd

map("n", "<leader>U", [[<cmd>PackerSync<cr>]], default_opts)
map("n", "<leader>M", [[<cmd>e ~/.config/nvim/lua/mappings.lua<cr>]], default_opts)
map("n", "<leader>S", [[<cmd>e ~/.config/nvim/lua/settings.lua<cr>]], default_opts)
map("n", "<leader>I", [[<cmd>e ~/.config/nvim/init.lua<cr>]], default_opts)
map("n", "<leader>a", [[<cmd>noh<cr>]], default_opts)
map("n", "<leader>h", [[<cmd>tabprevious<cr>]], default_opts)
map("n", "<leader>l", [[<cmd>tabnext<cr>]], default_opts)
map("n", "<leader>j", [[<cmd>bp<cr>]], default_opts)
map("n", "<leader>k", [[<cmd>bn<cr>]], default_opts)
map("n", "<leader>d", [[<cmd>bd<cr>]], default_opts)
map("n", "sf", [[<cmd>e .<cr>]], default_opts)
map("n", "ss", [[<cmd>split<cr>]], default_opts)
map("n", "sv", [[<cmd>vsplit<cr>]], default_opts)
map('n', 'te', '<cmd>tabedit<return>', default_opts)
map("n", "<leader>w", [[<Cmd>up<cr>]], default_opts)
map("n", "<leader>q", [[<Cmd>q<cr>]], default_opts)
map("n", "\\", [[<cmd>Neogit<cr>]], default_opts)
map("n", "<leader>g", [[<Cmd>lua require("telescope.builtin").live_grep()<cr>]], default_opts)
map("n", "<leader>e", [[<Cmd>lua require("telescope.builtin").find_files()<cr>]], default_opts)
map("n", ";", ":", default_opts)
map("i", "jk", "<esc>", default_opts)
map("i", "kj", "<esc>", default_opts)
map("n", [[<leader>u]], ":%! sort -uV<cr>", default_opts)
map('n', 'Y', 'y$', default_opts)
map('n', 'n', 'nzzzv', default_opts)
map('n', 'N', 'Nzzzv', default_opts)
map('n', 'J', 'mzJ`z', default_opts)
map('i', ',', ',<c-g>u', default_opts)
map('i', '.', '.<c-g>u', default_opts)
map('i', '!', '!<c-g>u', default_opts)
map('i', '?', ',<c-g>u', default_opts)
map('n', '<leader>i', 'gq<cr>', default_opts)
map('n', '<leader>s', '/', default_opts)
map('n', 'U', '<C-r>', default_opts)
map('n', 'sh', '<C-w>h', default_opts)
map('n', 'sj', '<C-w>j', default_opts)
map('n', 'sk', '<C-w>k', default_opts)
map('n', 'sl', '<C-w>l', default_opts)
map('n', 'e', '$', default_opts)
map('n', 'm', '%', default_opts)
