require("nvim-treesitter.configs").setup({
    highlight = { enable = true },
    indent = { enable = true },
    ensure_installed = {
        "go",
        "gomod",
        "python",
        "latex",
        "lua",
        "yaml",
        "json",
        "javascript",
        "bash",
        "typescript",
        "hcl",
        "make",
        "css",
        "tsx",
        "c",
        "cpp",
        "dockerfile",
        "bibtex",
        "java",
        "php",
        "solidity",
    },
})
